# $HOME/.config/alacritty/alacritty.toml
# by Rito Ghosh 2023-10-06

# Alacritty now uses TOML formatting for its config files.
# This is a simple example.

# There are the specification here: https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd
# It is not obvious how it translates to TOML. But it is extremely straightforward.

# example: WINDOW, COLORS, etc. are tables, and should be represented as [window], [colors], respectively.
# specifics of variables go under them. e.g.- look under "dynamic_padding" under-
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#window
# write `dynamic_padding = true` (without backticks -`) under the table [window]
# for variables with multiple values, use "dotted keys". Like setting `padding.x = 5` under [window].
# This is simple. If not clear, do several trials and errors.

# Below is my initial set-up. The TOML homepage (https://toml.io/en/v1.0.0) was very helpful in figuring this out. 
# I put the file alacritty.toml in $HOME/.config/alacritty. However it can be kept anywhere among the places mentioned in
# https://github.com/alacritty/alacritty/tree/master#configuration

# https://github.com/alacritty/alacritty-theme?tab=readme-ov-file --> themes
[general]
live_config_reload = true
import = [ "~/.config/alacritty/themes/themes/tokyo_night_enchanced.toml" ]
# import = [ "~/.config/alacritty/themes/themes/iterm.toml" ]

[window]
padding.x = 0
padding.y = 0
# history = 10000
# multiplier = 3
decorations = "none"



[font]
size = 7
# [font.normal]
# family = "JetBrainsMono Nerd Font"
# # style = "Medium"
# [font.bold]
# family = "JetBrainsMono Nerd Font"
# # style = "Heavy"
# [font.bold_italic]
# family = "JetBrainsMono Nerd Font"
# # style = "Heavy Italic"
# [font.italic]
# family = "JetBrainsMono Nerd Font"
# # style = "Medium Italic"




[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
